logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
